app:
  name: projectTest
jwt:
  header: Authorization
  expires_in: 3600 # 1 hours
  mobile_expires_in: 600 # 10 minutes
  secret: project
server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: ##YOUR_DB_USER
    password: ##YOUR_DB_PASSWORD
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: #YOUR_EMAIL_ADDRESS
    password: #YOUR_EMAIL_PASSWORD
    properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
  messages:
    basename: message
  profiles:
    include: generate-sample-data
custom:
  prop:
    max-page-size: 10
    support-email: #CONTACT_EMAIL_ADDRESS